<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>9d34b6b9-7497-4249-8782-78d7ee4c0bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snbSubMenu9']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#snbSubMenu9 > ul > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;채용홈페이지&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62277893-e2d2-4623-bed7-657ec48259c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mgt/recruitSite/basicInfo/basicInfo.do?menuId=90000300</value>
      <webElementGuid>bc6ef235-cb1c-4833-80e4-f46d16edd973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>채용홈페이지
            </value>
      <webElementGuid>cacef5de-b6c7-46d5-914b-cc6de4709fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snbSubMenu9&quot;)/ul[1]/li[3]/a[1]</value>
      <webElementGuid>53625628-7694-4236-ad41-49fba4a1dc44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='snbSubMenu9']/ul/li[3]/a</value>
      <webElementGuid>ce546836-6ac3-4ffe-80de-d2fb78c6a4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'채용홈페이지')]</value>
      <webElementGuid>45515cab-6554-49ee-b369-8fed99ed4f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사용자'])[1]/following::a[1]</value>
      <webElementGuid>5ce4fb07-71de-4dfa-9ff6-53b10de16d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업정보'])[2]/following::a[2]</value>
      <webElementGuid>acc0f4bc-539a-4bc8-b6e7-f9232c51ea19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인정보삭제기준'])[1]/preceding::a[1]</value>
      <webElementGuid>220319e6-00cb-4394-97cc-f36e1aa6cf73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='발송이력'])[1]/preceding::a[2]</value>
      <webElementGuid>12cbe138-3701-4589-a476-667feb67e146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='채용홈페이지']/parent::*</value>
      <webElementGuid>dbd5b153-c5d0-4a02-a3c8-f58cf501d9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mgt/recruitSite/basicInfo/basicInfo.do?menuId=90000300')]</value>
      <webElementGuid>a90c48c9-a1a2-4405-9cca-a93ed214a732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li[3]/a</value>
      <webElementGuid>fe2392b8-1ab8-4088-821e-b8ffcef98ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mgt/recruitSite/basicInfo/basicInfo.do?menuId=90000300' and (text() = '채용홈페이지
            ' or . = '채용홈페이지
            ')]</value>
      <webElementGuid>20228771-12d7-4821-a3b5-d7826abe027e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
