<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>82fcbbf5-49a6-49a0-9704-a8760cefa31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='qnaTable']/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qnaTable > tbody > tr.odd > td.dt-head-center > a.point-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;내용테스트입니다&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07ec0bac-183f-48d3-8a10-7f619663bf37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>point-color</value>
      <webElementGuid>f36b83ed-bbc0-4305-936b-14db0ffd5a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:goQnaDetailPage('973', 'N')</value>
      <webElementGuid>e2e16bec-c87d-4f1d-a842-c54b60bfacda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>내용테스트입니다</value>
      <webElementGuid>317c8342-6dd4-40fb-a571-33bbc51ba4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qnaTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-head-center&quot;]/a[@class=&quot;point-color&quot;]</value>
      <webElementGuid>cd833730-bb66-438d-b4cd-b2dd4525ca12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='qnaTable']/tbody/tr/td[3]/a</value>
      <webElementGuid>4af1f4b5-071b-4ddd-8d18-c227b83b0ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'내용테스트입니다')]</value>
      <webElementGuid>3a1f5215-5775-4829-b0f3-4e077d5036e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='선택'])[18]/following::a[1]</value>
      <webElementGuid>ed0ada73-9337-430d-bd2e-d0c76701a33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='최종답변정보'])[1]/following::a[1]</value>
      <webElementGuid>e4989531-c5d1-4ef8-b80a-33e2a8b30454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='공승민'])[1]/preceding::a[1]</value>
      <webElementGuid>69880d70-bacc-442b-a06b-8ca800a52c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='선택'])[19]/preceding::a[1]</value>
      <webElementGuid>15ed3db9-7946-4361-bbc4-d5a490cf9518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='내용테스트입니다']/parent::*</value>
      <webElementGuid>bd63e29e-1c82-4c6e-849e-a84e65608417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:goQnaDetailPage('973', 'N')&quot;)]</value>
      <webElementGuid>837021fa-dca7-4905-847b-11a807eb992b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/div/table/tbody/tr/td[3]/a</value>
      <webElementGuid>c69307b1-a6ca-4d86-8485-de931b37e4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:goQnaDetailPage(&quot; , &quot;'&quot; , &quot;973&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;N&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '내용테스트입니다' or . = '내용테스트입니다')]</value>
      <webElementGuid>8868b3e3-14b5-424f-9d94-4c80c476b06d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
