<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_</name>
   <tag></tag>
   <elementGuidId>70199cfc-773f-40d9-9177-3e0f2c19b4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='txtQnaPopupTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtQnaPopupTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;내용테스트입니다&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0327e552-f1c8-423b-affe-d59066777f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-sub</value>
      <webElementGuid>18957352-2701-4efd-a50b-2397972a1dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtQnaPopupTitle</value>
      <webElementGuid>563cf924-01e7-4018-8c3d-cb417c175243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>내용테스트입니다</value>
      <webElementGuid>40deb65c-0867-4c2b-acf4-7f697fd80341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtQnaPopupTitle&quot;)</value>
      <webElementGuid>57823166-bbd6-48d8-ae58-a6e887f0f1cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='txtQnaPopupTitle']</value>
      <webElementGuid>0e9f4948-3c2a-418e-9b11-3c68d8b373df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WAP-ETPR-0130']/div/div[3]/div/section/div[2]/div/h3</value>
      <webElementGuid>2a774f8d-b34d-4eb6-9168-01e248656c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='미응답'])[1]/following::h3[1]</value>
      <webElementGuid>9e99aafc-ad69-4cf7-a8bc-d68670a053e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='응답완료'])[1]/following::h3[1]</value>
      <webElementGuid>e5b95183-3039-415e-8546-0b9331a436c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='내용테스트입니다'])[3]/preceding::h3[1]</value>
      <webElementGuid>0c3f6504-0d9c-43da-8516-0be38e508fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='수정'])[4]/preceding::h3[1]</value>
      <webElementGuid>b667491d-8c24-467d-94bc-0e19db497656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/div/section/div[2]/div/h3</value>
      <webElementGuid>cb6a1bce-1bf0-494e-a71d-64b2513e1b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'txtQnaPopupTitle' and (text() = '내용테스트입니다' or . = '내용테스트입니다')]</value>
      <webElementGuid>25b77fc4-0bb9-4141-8f28-b077d5653fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
