<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>2ca0d69c-5203-4f17-8914-c86c91578039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='resultList']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.base-btn.type2__size-s2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#resultList div >> internal:has-text=&quot;종료 [test] 채용공고등록테스트240305 (~2024.03.05) 자세히보기 지원자수 0명&quot;i >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98b90e2e-362c-4a75-8765-d45bb064c800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:detailPage(723)</value>
      <webElementGuid>b864d39e-471c-4774-85cc-0a82fd2b0b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type2__size-s2</value>
      <webElementGuid>3cb5249c-5cfc-441c-8a54-523a57017ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>자세히보기</value>
      <webElementGuid>a9ac6601-55a3-40ed-b593-da5b94126c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultList&quot;)/div[@class=&quot;box-type2 employ-progress__box&quot;]/div[@class=&quot;employ-progress__header&quot;]/div[@class=&quot;employ-progress__header__cell&quot;]/a[@class=&quot;base-btn type2__size-s2&quot;]</value>
      <webElementGuid>bb56c846-4784-4d0a-a434-3bd5d4335f3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='resultList']/div/div/div/a</value>
      <webElementGuid>cd043492-79bb-4ca4-be11-011e86482cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'자세히보기')]</value>
      <webElementGuid>19876e6c-6bb7-43fc-ba87-35f2f9f6ee38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[test] 채용공고등록테스트240305 (~2024.03.05)'])[1]/following::a[1]</value>
      <webElementGuid>3290eac7-7915-4135-ae2a-fe86d46502fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='종료'])[2]/following::a[1]</value>
      <webElementGuid>2e382592-d819-4d81-a42f-5b8a59463f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지원자수'])[1]/preceding::a[1]</value>
      <webElementGuid>8f8fc517-6ac8-4680-ba68-d0ec22f501f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='종료'])[3]/preceding::a[1]</value>
      <webElementGuid>6e12336f-94e0-4229-866b-3bf28318873c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='자세히보기']/parent::*</value>
      <webElementGuid>925c6d52-b9f5-4d67-a409-5ff6e7d80d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:detailPage(723)')]</value>
      <webElementGuid>d342ca64-14ed-4693-bd38-2f1cbf8eab62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>08600f0d-504b-47f0-9cb7-a1c5494f9050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:detailPage(723)' and (text() = '자세히보기' or . = '자세히보기')]</value>
      <webElementGuid>4866963b-7720-4bee-be63-efa0f33db500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
