<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>9d34b6b9-7497-4249-8782-78d7ee4c0bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snbSubMenu10']/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a.isMark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;도움말관리&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38d84740-e9dc-42ac-9f03-3ca38bd69feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/orp/management/help/list.do?menuId=40000500</value>
      <webElementGuid>6eb38485-bd9b-4566-a838-eecbf3a7a013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>isMark</value>
      <webElementGuid>bfd77182-65ae-44ab-bcc8-e9c057ebef7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>도움말관리
            </value>
      <webElementGuid>681fda20-34e5-4d2d-b458-eb4801179608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snbSubMenu10&quot;)/ul[1]/li[5]/a[@class=&quot;isMark&quot;]</value>
      <webElementGuid>d5867f12-dd54-40e3-bdd5-34f7bf4ee02d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='snbSubMenu10']/ul/li[5]/a</value>
      <webElementGuid>f9f50442-1794-425f-bfe3-1e532667e36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'도움말관리')]</value>
      <webElementGuid>9dae4db0-ef4e-4b7f-981c-792e482d24e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='권한관리'])[1]/following::a[1]</value>
      <webElementGuid>bafe71c4-896b-4ce8-aaa3-36b0371a2db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사용자관리'])[1]/following::a[2]</value>
      <webElementGuid>8f3f6a42-e78c-4c85-ac88-b4f8f63fca21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='접속기록'])[1]/preceding::a[1]</value>
      <webElementGuid>94888546-8238-424c-a748-c12af0ce702e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='축소/확대 버튼'])[1]/preceding::a[2]</value>
      <webElementGuid>92664cf9-1edc-4ba0-8fc8-004144a625f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='도움말관리']/parent::*</value>
      <webElementGuid>9666e69f-55dc-48a7-b4d9-ea4bba7eecdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/orp/management/help/list.do?menuId=40000500')]</value>
      <webElementGuid>ecef069c-5e56-4c3a-b75e-853282d2f081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[5]/a</value>
      <webElementGuid>4b534a98-c5bd-48fa-a863-2335ce501b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/orp/management/help/list.do?menuId=40000500' and (text() = '도움말관리
            ' or . = '도움말관리
            ')]</value>
      <webElementGuid>263a21bd-f692-44b4-b869-622de5221e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
