<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>565d170b-f115-46bf-b593-34b93e71270e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.popup__container.isShow > div.popup__btn-wrap > button.base-btn.type1__size-m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='안내'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;확인&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2d88aa2-04b2-4afc-bce5-88b323b44a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type1__size-m</value>
      <webElementGuid>134ecf98-8ddd-4cd4-8722-1c09fd965ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnConfirm</value>
      <webElementGuid>42bdea42-085b-44c0-8f8f-69ff48f46755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>확인</value>
      <webElementGuid>a322da89-ed02-4e4d-be1b-8d2716dbaf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;isLayerShow&quot;]/div[@class=&quot;layer-popup type-modal isShow&quot;]/section[@class=&quot;popup__container isShow&quot;]/div[@class=&quot;popup__btn-wrap&quot;]/button[@class=&quot;base-btn type1__size-m&quot;]</value>
      <webElementGuid>4b364e89-fc08-4a80-b34a-42e6863d94c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='안내'])[1]/following::button[1]</value>
      <webElementGuid>bd21c768-8258-41b7-9f0e-234635d9e2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer 영역입니다.'])[1]/following::button[1]</value>
      <webElementGuid>970d836b-eac5-4f0b-8861-aa88f0b703fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='닫기'])[5]/preceding::button[1]</value>
      <webElementGuid>4423e863-768b-4791-9a5a-752f8bb56ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='확인']/parent::*</value>
      <webElementGuid>dc54b5e9-f8fe-4f59-8330-5011e853866e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/section/div[3]/button</value>
      <webElementGuid>43d9286d-faa3-4cf6-81c2-81daa92db8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '확인' or . = '확인')]</value>
      <webElementGuid>ebc77ea9-a889-4555-8ebd-c572c3891055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
