<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>97fcf0d5-f9fe-4162-bc94-fe43b9470286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0010-ScrnAddDocument</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='WAP-EMPL-0010-ScrnAddDocument']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;서류전형&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0afd5c0-83cc-442d-9d89-415207d491b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type2__size-s</value>
      <webElementGuid>bd4312f7-67cd-4778-9f75-21d12b49383b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0010-ScrnAddDocument</value>
      <webElementGuid>1a987d69-e19b-4517-80c9-63f78c174f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addSelection('document')</value>
      <webElementGuid>f5131011-8593-4d78-bfdb-efb8b08c5081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							서류전형
						</value>
      <webElementGuid>d0070a02-c831-431f-b46b-23922d6cf117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0010-ScrnAddDocument&quot;)</value>
      <webElementGuid>93908d81-6ae6-41cc-86f8-4f5a446a219a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='WAP-EMPL-0010-ScrnAddDocument']</value>
      <webElementGuid>427da2f8-33e3-4c6c-91c2-ac1f4794e43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addSelection']/div/div[2]/div/button</value>
      <webElementGuid>f8ebb422-d20d-4053-8855-2e1e2a9346ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전형 추가'])[1]/following::button[1]</value>
      <webElementGuid>6dd4b3d0-1b96-4ef4-bf7f-ee766e1f00bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전형설계'])[2]/following::button[1]</value>
      <webElementGuid>9e2fe809-9d25-40c6-a86e-bac22632597c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='필기전형'])[1]/preceding::button[1]</value>
      <webElementGuid>9e244eeb-5370-43ae-ad7b-29c9f0544501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[2]/div/div[2]/div/button</value>
      <webElementGuid>d84bb348-71cf-414a-b2d3-0d82e903b46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'WAP-EMPL-0010-ScrnAddDocument' and (text() = '
							서류전형
						' or . = '
							서류전형
						')]</value>
      <webElementGuid>94a1971d-617e-4e54-8c13-2cd99db9b7d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
