<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_</name>
   <tag></tag>
   <elementGuidId>e33db862-4559-4144-93b3-0804a3edf93d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='txtQnaPopupTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtQnaPopupTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;내용테스트입니다&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>c0080441-ef8a-4d02-b6f7-b10f44738d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-sub</value>
      <webElementGuid>bc8fb8de-6f5e-4642-bcff-cda3d5212731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtQnaPopupTitle</value>
      <webElementGuid>2fa73208-b25b-4fab-9bdf-3872f1752267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>내용테스트입니다</value>
      <webElementGuid>290ee521-a834-4adc-a62a-944461029b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtQnaPopupTitle&quot;)</value>
      <webElementGuid>a82d08a7-7c27-4e7d-bcaa-483b802564d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='txtQnaPopupTitle']</value>
      <webElementGuid>2db9a2f1-454c-4938-950d-1b39ff1c79b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WAP-ETPR-0130']/div/div[3]/div/section/div[2]/div/h3</value>
      <webElementGuid>18f7925f-6f60-4018-9a2e-3876dc0da0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='미응답'])[1]/following::h3[1]</value>
      <webElementGuid>91073468-0065-40e0-a04f-340a8cef1988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='응답완료'])[1]/following::h3[1]</value>
      <webElementGuid>4d278048-1e4c-42b8-8097-b59dceb48e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='내용테스트입니다'])[3]/preceding::h3[1]</value>
      <webElementGuid>bd79454d-57fa-4a17-a7ae-ae7cd392d3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='수정'])[4]/preceding::h3[1]</value>
      <webElementGuid>c2f47d8b-f63f-42ca-bf3c-d7fb7fccb273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/div/section/div[2]/div/h3</value>
      <webElementGuid>8c1a4510-5a49-4348-850a-5b6b83c15602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'txtQnaPopupTitle' and (text() = '내용테스트입니다' or . = '내용테스트입니다')]</value>
      <webElementGuid>a7678124-a062-499e-b0cc-045acc593c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
