<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__tx_canvas_wysiwyg0</name>
   <tag></tag>
   <elementGuidId>70a7ba68-a982-43bc-aaf6-a6bbe1556d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_canvas_wysiwyg0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_canvas_wysiwyg0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;tx_canvas_wysiwyg0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>44e00770-773f-491e-8733-05e318b6291b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_canvas_wysiwyg0</value>
      <webElementGuid>c4b83c17-b853-4792-aacc-543330de77c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_canvas_wysiwyg0</value>
      <webElementGuid>480da2c6-f490-4931-8a90-238730397dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7edac704-915a-42e4-83bb-9d0c11d9d0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>238ca886-0160-4c54-9d13-5a6ed4337cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>에디터 영역 : 에디터 영역에서 빠져 나오시려면 Shift+ESC키를 누르세요</value>
      <webElementGuid>9b5506de-da67-4120-b7c2-d1246428bc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_canvas_wysiwyg0&quot;)</value>
      <webElementGuid>e0fd8cc8-c885-4006-a02c-28500ee90d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_canvas_wysiwyg0']</value>
      <webElementGuid>09ab7e05-0f05-4358-a4aa-68d635125402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tx_canvas_wysiwyg_holder0']/iframe</value>
      <webElementGuid>d0472726-c870-415e-9d7f-fac8c4c61c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ef917133-1f03-4e58-947b-2278f5ef0369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tx_canvas_wysiwyg0' and @name = 'tx_canvas_wysiwyg0' and @title = '에디터 영역 : 에디터 영역에서 빠져 나오시려면 Shift+ESC키를 누르세요']</value>
      <webElementGuid>8bf332aa-c7b1-4fe2-a758-bc52f061c48b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
