<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__calendar1_1</name>
   <tag></tag>
   <elementGuidId>3f23d574-8d9d-4e7a-867a-1bb4594a70b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendar1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calendar1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#calendar1_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78de92e2-bebe-4e08-89e8-1172ed9219c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2507652a-5507-4c75-a5bc-917ca61701e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt datepicker-input</value>
      <webElementGuid>b3bf95dc-c23c-4051-87af-42bf0196d040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar1_1</value>
      <webElementGuid>6c5c7119-0877-416f-a1b9-0883801a587e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>일자 선택</value>
      <webElementGuid>19c6864e-c2df-4a38-823b-36402c3e8fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7a9b80b5-0afe-44a1-a12a-c49676c63a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar1_1&quot;)</value>
      <webElementGuid>e7549319-a20e-4ece-81b8-c292e32e0d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calendar1_1']</value>
      <webElementGuid>dbe8c922-b73a-4a60-9fa4-ed55266c90b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>b16b089e-debd-4d78-96e5-57a18cfe4b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'calendar1_1' and @placeholder = '일자 선택']</value>
      <webElementGuid>7d57228a-dcc7-43f3-b377-4f03f7c1d20c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
