<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__calendar1_2</name>
   <tag></tag>
   <elementGuidId>37c8907a-99f7-41fc-a95e-701117007e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendar1_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calendar1_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#calendar1_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89706cff-937d-401c-ab74-a52210b3e5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b76be6f7-7cda-4a0a-a6bb-5d0db4e5f7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt datepicker-input</value>
      <webElementGuid>fdfc5a41-f59a-4b4f-97a9-fb76e3e014ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar1_2</value>
      <webElementGuid>b0cc6664-65a2-449f-bf79-7ce2c3ec08d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>일자 선택</value>
      <webElementGuid>ce0120c5-eec0-4a0e-83e7-4b3317b01677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08cbf915-3422-4599-b1ee-edfb4c69eb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar1_2&quot;)</value>
      <webElementGuid>7e5102c2-c422-43ad-b039-5530e0069a7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calendar1_2']</value>
      <webElementGuid>bc517b85-7d10-422a-ba0d-2562414c3779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>617c2963-1cae-4bb8-894a-d7c041b41a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'calendar1_2' and @placeholder = '일자 선택']</value>
      <webElementGuid>6bdacbdc-78c3-4fef-b139-2be52d1acbd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
