<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__departmentName</name>
   <tag></tag>
   <elementGuidId>508d0e21-40ea-4c09-b284-721b75e98934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#departmentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='departmentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;채용분야 검색&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2c6a4bf-cdf5-4731-b34c-47120da67960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b149296-0ff5-4f13-a2c9-c74db47cb1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt</value>
      <webElementGuid>456bd944-4e9f-48d7-8a41-a4151a1a563a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>departmentName</value>
      <webElementGuid>4008cc8a-1272-47ed-9d04-28d2ed63cb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>inputValueChk()</value>
      <webElementGuid>eab9a24e-f452-44a8-bace-8e126a8e1958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>채용분야 검색</value>
      <webElementGuid>1cb93361-ef8a-4cb0-ae31-ede0bba30006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:if(event.keyCode==13) { addField() }</value>
      <webElementGuid>718fab62-aa25-4a80-b1db-8d508a654e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departmentName&quot;)</value>
      <webElementGuid>119af282-c071-48ad-ada9-1467ec49598f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='departmentName']</value>
      <webElementGuid>5c019919-4010-4bc6-a8ef-d284a1306ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>1320f11a-998b-4a40-82a4-30db0c79a109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'departmentName' and @placeholder = '채용분야 검색']</value>
      <webElementGuid>7eeb1c3e-806f-4d19-9695-843bf0916794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
