<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pre_</name>
   <tag></tag>
   <elementGuidId>2c17da7f-e072-4951-b859-0ac52ae6e27b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//pre[@id='tbxQnaContents']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tbxQnaContents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tbxQnaContents</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>pre</value>
      <webElementGuid>7c11b283-d33c-45ba-aaf2-a97ebb124779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-size-l</value>
      <webElementGuid>b6fb1739-48b6-4bf2-b077-aa2b6e3e7c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbxQnaContents</value>
      <webElementGuid>e706c0a8-8c33-4b3c-bbc0-c329e980cce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>내용테스트입니다</value>
      <webElementGuid>d68330a9-f325-4c02-ac90-3909dbdffc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbxQnaContents&quot;)</value>
      <webElementGuid>41b112e5-3c8a-4821-9c99-581e24cf8a46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//pre[@id='tbxQnaContents']</value>
      <webElementGuid>a5cdf22a-61fe-4943-bf90-c7e851d2f86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WAP-ETPR-0130']/div/div[3]/div/section/div[2]/div[2]/pre</value>
      <webElementGuid>5e867db1-1d9f-4123-a497-4a863328ad60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='내용테스트입니다'])[2]/following::pre[1]</value>
      <webElementGuid>3eb06b2e-0277-4b42-8baa-b882dda89131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='미응답'])[1]/following::pre[1]</value>
      <webElementGuid>308a378b-65e7-4a18-9117-5e350a3b3454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='수정'])[4]/preceding::pre[2]</value>
      <webElementGuid>071a4e6c-b5ee-4079-846d-185bf56a87ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='답변달기'])[1]/preceding::pre[2]</value>
      <webElementGuid>9f89e619-94b4-46ee-a2fc-3f7d9c534fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/pre</value>
      <webElementGuid>8d3e7267-6955-4aa7-a3d8-a5a0595d2f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//pre[@id = 'tbxQnaContents' and (text() = '내용테스트입니다' or . = '내용테스트입니다')]</value>
      <webElementGuid>7229c060-d2c0-4c48-bce4-e574269fc877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
