<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>c02405da-5477-4d5c-bb4d-7770a3a52c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='treeDemo_4_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#treeDemo_4_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;채용관리&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4afd05cd-3c94-4c03-860f-c1ef5b3e7acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeDemo_4_span</value>
      <webElementGuid>86cdf686-7d33-4068-919e-48137b842116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node_name</value>
      <webElementGuid>85e85e7e-4b95-487d-bcd7-2a9f2ebb4b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>채용관리</value>
      <webElementGuid>1266bd93-79ac-4288-8797-2634d539a5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeDemo_4_span&quot;)</value>
      <webElementGuid>11a8cd97-7ba3-4d5f-9380-95db1707a765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='treeDemo_4_span']</value>
      <webElementGuid>30e1c6fa-7b59-49b5-ba62-82a88cec21d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='treeDemo_4_a']/span[2]</value>
      <webElementGuid>c3ca3ea2-3e09-449a-a0e2-00464f6f7c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업관리'])[4]/following::span[3]</value>
      <webElementGuid>b01bc913-7638-4d30-8ae9-1c553cc1cfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업관리'])[3]/following::span[6]</value>
      <webElementGuid>3663e135-4bc6-4faa-a266-6052b2f1716d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='콘텐츠관리'])[2]/preceding::span[3]</value>
      <webElementGuid>a7bd377b-ddbb-4774-8a5c-872f2fe8b8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='입사지원서'])[2]/preceding::span[6]</value>
      <webElementGuid>a5ee27b6-0622-48e8-a664-eb2ec99ea4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[2]/a/span[2]</value>
      <webElementGuid>a28c8328-4fcf-4735-a377-62930982dc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'treeDemo_4_span' and (text() = '채용관리' or . = '채용관리')]</value>
      <webElementGuid>bd9a6222-5f9a-4f76-8041-11a2537c24ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
