<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__treeDemo_1_switch</name>
   <tag></tag>
   <elementGuidId>7a1ce45c-5675-4070-8b9f-cf03ddd68746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='treeDemo_1_switch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#treeDemo_1_switch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#treeDemo_1_switch</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3dcc482-f6c8-4944-9d87-1394bf215d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeDemo_1_switch</value>
      <webElementGuid>7f653c5a-a672-4ddc-8b28-9240078c0590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button level0 switch roots_close</value>
      <webElementGuid>c514fb55-b606-471e-9e7e-d11f59713da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeDemo_1_switch&quot;)</value>
      <webElementGuid>a835b1bf-3848-4367-9484-a2c3e8de076b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='treeDemo_1_switch']</value>
      <webElementGuid>a0bb3d45-f595-4995-a990-19fc9e8b4547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='treeDemo_1']/span</value>
      <webElementGuid>bb38b773-ee45-4ff0-a6c4-35bc5fda4a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li/span</value>
      <webElementGuid>5d27466d-15f9-447a-959a-659a25df8203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'treeDemo_1_switch']</value>
      <webElementGuid>44e7a7c9-2c2a-4fbb-a25f-cb6269840ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
