<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>600227c2-653f-4a20-b2bc-44f753c87458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snbSubMenu10']/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a.isMark</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/orp/management/help/list.do?menuId=40000500' and (text() = '도움말관리
            ' or . = '도움말관리
            ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;도움말관리&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19b222a5-a84c-432b-b477-9f505e15b1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/orp/management/help/list.do?menuId=40000500</value>
      <webElementGuid>b4b686f9-c8de-40e2-92c5-ae0da8da1da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>isMark</value>
      <webElementGuid>d0ae0352-8634-422d-bed1-57c6686c4ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>도움말관리
            </value>
      <webElementGuid>0702ea6f-d325-4dc5-8e36-d03d3d12be5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snbSubMenu10&quot;)/ul[1]/li[5]/a[@class=&quot;isMark&quot;]</value>
      <webElementGuid>ba4c3a4a-0377-42f2-91e6-fc9239946790</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='snbSubMenu10']/ul/li[5]/a</value>
      <webElementGuid>bbe4e646-139f-4db2-a8d1-a183f83e8c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'도움말관리')]</value>
      <webElementGuid>d4e33d7b-3846-4899-8a92-d735520590ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='권한관리'])[1]/following::a[1]</value>
      <webElementGuid>fecdf3a0-9c8a-4302-9c50-c919d22a0826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사용자관리'])[1]/following::a[2]</value>
      <webElementGuid>c58b0bd4-b5c1-4cc6-b046-590af0622061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='접속기록'])[1]/preceding::a[1]</value>
      <webElementGuid>e97017c8-654b-4bed-ac09-32be68bb7fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='축소/확대 버튼'])[1]/preceding::a[2]</value>
      <webElementGuid>be088484-4a6e-4226-b998-2a7810bb7d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='도움말관리']/parent::*</value>
      <webElementGuid>38df6dd4-43d0-4e0a-b1c2-2078c8d6217c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/orp/management/help/list.do?menuId=40000500')]</value>
      <webElementGuid>a0904871-9169-4515-b674-ad71599e283b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[5]/a</value>
      <webElementGuid>af3fd4bb-cd72-4213-a805-b19666ad8b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/orp/management/help/list.do?menuId=40000500' and (text() = '도움말관리
            ' or . = '도움말관리
            ')]</value>
      <webElementGuid>711b363d-830c-4f61-b1be-86f95b86541a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
