<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>67479ae4-af6d-44ba-bce1-c303b309cc3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='treeDemo_4_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#treeDemo_4_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;채용관리&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d45eb81-695b-43e1-a263-d3caf05f755e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeDemo_4_span</value>
      <webElementGuid>cc0eecd6-72ce-4eff-94e5-03f7632a1e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node_name</value>
      <webElementGuid>1fcd1558-287f-4f16-bc02-7ecbc22b471e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>채용관리</value>
      <webElementGuid>b1bd9c33-48cb-41ab-9c09-766586139b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeDemo_4_span&quot;)</value>
      <webElementGuid>bb12f9ee-2756-46bc-9ff0-cd50036eb52c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='treeDemo_4_span']</value>
      <webElementGuid>18e0860f-ba7d-4095-96b4-a1b6cc83444e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='treeDemo_4_a']/span[2]</value>
      <webElementGuid>1452bcdc-883d-4f06-af34-6f46f85e755b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업관리'])[4]/following::span[3]</value>
      <webElementGuid>18ae37e8-4d97-4f82-b54a-3355e19666cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업관리'])[3]/following::span[6]</value>
      <webElementGuid>6c32b65f-b4c7-498e-9ef1-bafe91842478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='콘텐츠관리'])[2]/preceding::span[3]</value>
      <webElementGuid>2d37ea26-8ad2-45d4-8f65-565b06aa2392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='입사지원서'])[2]/preceding::span[6]</value>
      <webElementGuid>977aa0f0-da58-44ad-938a-83dc2d836729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[2]/a/span[2]</value>
      <webElementGuid>7d61b536-dbc7-42d5-955e-3c8f3af6e8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'treeDemo_4_span' and (text() = '채용관리' or . = '채용관리')]</value>
      <webElementGuid>c95fbcce-f05b-47f9-afe5-dba0a20466f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
