<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__treeDemo_1_switch</name>
   <tag></tag>
   <elementGuidId>724281ae-32b1-45a9-bb28-c66a70c6946f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='treeDemo_1_switch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#treeDemo_1_switch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#treeDemo_1_switch</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6350d0e8-315d-4fde-a33e-e8869b233846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeDemo_1_switch</value>
      <webElementGuid>ca641b70-403d-4986-9145-84da1614fb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button level0 switch roots_close</value>
      <webElementGuid>4be9f112-fab0-4371-8e0b-4b2c0eaa0775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeDemo_1_switch&quot;)</value>
      <webElementGuid>a3d650b5-b3d6-4b50-bda1-94a90b34a6e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='treeDemo_1_switch']</value>
      <webElementGuid>593cdf94-4d51-4dce-8a99-cc7dace71ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='treeDemo_1']/span</value>
      <webElementGuid>7e5ba40c-7d89-4133-8202-bb68ec3e0b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li/span</value>
      <webElementGuid>25b46aa9-92a3-4fef-8d4d-43e655791ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'treeDemo_1_switch']</value>
      <webElementGuid>277502b0-1013-4220-a3b0-e3a8cc170c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
