<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>자세히보기버튼</name>
   <tag></tag>
   <elementGuidId>f667924b-0957-4528-8b01-59bdae2d5cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='resultList']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.base-btn.type2__size-s2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#resultList div >> internal:has-text=&quot;종료 [test] 채용공고등록테스트240305 (~2024.03.05) 자세히보기 지원자수 0명&quot;i >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91e52634-9d65-4cb2-8709-3ab9becb2760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:detailPage(723)</value>
      <webElementGuid>48409cae-eda1-4634-aae5-32c3a78a62d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type2__size-s2</value>
      <webElementGuid>57d6fed5-49c1-4bc3-8bc1-4e1fa1d4b446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>자세히보기</value>
      <webElementGuid>6447545a-ff85-4b47-9cd0-116db891b894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultList&quot;)/div[@class=&quot;box-type2 employ-progress__box&quot;]/div[@class=&quot;employ-progress__header&quot;]/div[@class=&quot;employ-progress__header__cell&quot;]/a[@class=&quot;base-btn type2__size-s2&quot;]</value>
      <webElementGuid>9a69b6c5-8beb-4639-b8d2-b3a8d709fec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='resultList']/div/div/div/a</value>
      <webElementGuid>4d51ffb1-5a83-44ec-a963-33dc7ef0a8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'자세히보기')]</value>
      <webElementGuid>55425e7e-42e2-4a9d-b0f1-2461fdf14601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[test] 채용공고등록테스트240305 (~2024.03.05)'])[1]/following::a[1]</value>
      <webElementGuid>3b02c836-3d8c-45f3-b1ec-e93f07117965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='종료'])[2]/following::a[1]</value>
      <webElementGuid>2532f4e0-9370-4ce6-8b36-fab1b670c1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지원자수'])[1]/preceding::a[1]</value>
      <webElementGuid>2c7a68bc-06fd-4b6e-8148-5f69175481b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='종료'])[3]/preceding::a[1]</value>
      <webElementGuid>7ca4125d-bc7a-46c2-b21e-3657964c51d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='자세히보기']/parent::*</value>
      <webElementGuid>babad303-a1be-4250-ae4d-0e26b8baa4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:detailPage(723)')]</value>
      <webElementGuid>e97abf1a-3c94-48dd-b8dd-2fa4221b353c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>268467b9-e1d5-48de-a49b-1eae8414812a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:detailPage(723)' and (text() = '자세히보기' or . = '자세히보기')]</value>
      <webElementGuid>5cfea5bd-4d4e-4958-9546-4cc394b199f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
