<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>자세히보기버튼</name>
   <tag></tag>
   <elementGuidId>2c407b5a-e65e-4fa4-b971-43a46db2c6ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='resultList']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.base-btn.type2__size-s2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#resultList div >> internal:has-text=&quot;종료 [test] 채용공고등록테스트240305 (~2024.03.05) 자세히보기 지원자수 0명&quot;i >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f73a064e-b8d2-47cb-a492-3035205f17f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:detailPage(723)</value>
      <webElementGuid>4119f9d2-fbcd-44f2-9a81-7effc761c732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type2__size-s2</value>
      <webElementGuid>73eb3cbc-b860-4363-aed1-fd900a10349c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>자세히보기</value>
      <webElementGuid>582b533c-19c5-4300-94da-923ef57d6fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultList&quot;)/div[@class=&quot;box-type2 employ-progress__box&quot;]/div[@class=&quot;employ-progress__header&quot;]/div[@class=&quot;employ-progress__header__cell&quot;]/a[@class=&quot;base-btn type2__size-s2&quot;]</value>
      <webElementGuid>f3411e65-0f58-4ce3-8aa2-65c9051e0f85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='resultList']/div/div/div/a</value>
      <webElementGuid>6b1b1dc7-475f-4197-b60d-0e3d35debcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'자세히보기')]</value>
      <webElementGuid>113fc139-cb99-497f-901e-0b4f1ed320bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[test] 채용공고등록테스트240305 (~2024.03.05)'])[1]/following::a[1]</value>
      <webElementGuid>1a6e91c2-651b-4547-a5b1-8977fd60f219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='종료'])[2]/following::a[1]</value>
      <webElementGuid>9ef14902-01d3-470d-b661-9f2c9aca9d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지원자수'])[1]/preceding::a[1]</value>
      <webElementGuid>8cffc24f-54be-4b43-ac56-5786f5a4d940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='종료'])[3]/preceding::a[1]</value>
      <webElementGuid>b8256620-0c1a-428a-9048-abf43765690d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='자세히보기']/parent::*</value>
      <webElementGuid>517adedd-7065-4e58-b48e-fbc1c844399e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:detailPage(723)')]</value>
      <webElementGuid>3e441440-10eb-4a13-946f-5063cd318081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>bbdb6d0d-853f-41cb-9bc6-0bb475ec7952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:detailPage(723)' and (text() = '자세히보기' or . = '자세히보기')]</value>
      <webElementGuid>0f1ebefe-ee87-42af-aabd-85e70e41eff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
