<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_기업정보메뉴</name>
   <tag></tag>
   <elementGuidId>dca11c69-568d-456c-815e-ed78b581391e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snbSubMenu9']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#snbSubMenu9 > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;기업정보&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2bcea5f9-6784-420b-8385-1faf07631afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/orp/management/company/show.do?menuId=90000100</value>
      <webElementGuid>507e2874-af4e-4dfe-9f28-d82014cea305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>기업정보
            </value>
      <webElementGuid>06f7ef56-203e-4e2b-bfae-115123f602b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snbSubMenu9&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>ee10918b-7d5c-4dba-ad6e-1fe6e98e600c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='snbSubMenu9']/ul/li/a</value>
      <webElementGuid>ce33af99-db0f-462f-a77d-52826b8e1b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'기업정보')]</value>
      <webElementGuid>4fe45dcf-c4e3-468c-b160-0624342d48d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업정보'])[1]/following::a[1]</value>
      <webElementGuid>6d19dada-4864-4f32-abb4-79ffc2742bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='만족도조사'])[1]/following::a[1]</value>
      <webElementGuid>29672752-ad28-4ee1-ac05-02a6a8688895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사용자'])[1]/preceding::a[1]</value>
      <webElementGuid>379c9229-ada6-4a66-84a6-61090da3022e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='채용홈페이지'])[1]/preceding::a[2]</value>
      <webElementGuid>cc31ad78-3681-415e-b3e0-2c0bd4da69d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/orp/management/company/show.do?menuId=90000100')]</value>
      <webElementGuid>1c070456-7ff6-4d8e-b2d5-5b7cec5478f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li/a</value>
      <webElementGuid>dc078f2a-e828-43fe-a30c-ff243c713dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/orp/management/company/show.do?menuId=90000100' and (text() = '기업정보
            ' or . = '기업정보
            ')]</value>
      <webElementGuid>e402160e-9704-4b5a-bc8c-1f801c74d749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
