<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>bbbe3dfd-b4e5-460e-822f-7b35a78ec200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='WAP_CORP_0020.hide()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.popup__container.popup__size-l.isShow > button.btn-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;닫기&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7c160c8-30cb-449d-9e08-c785db723f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close</value>
      <webElementGuid>ca004295-7a99-42f3-aabb-754c3e074395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>WAP_CORP_0020.hide()</value>
      <webElementGuid>0ee768d2-6055-4179-b427-2013d1333340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>닫기</value>
      <webElementGuid>d3bbf5cf-7ac3-4eb3-98d1-1b0813258121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;isLayerShow&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;layer-popup type-modal isShow&quot;]/section[@class=&quot;popup__container popup__size-l isShow&quot;]/button[@class=&quot;btn-close&quot;]</value>
      <webElementGuid>3b460d64-0e04-47cb-a7ae-7277886ee107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='WAP_CORP_0020.hide()']</value>
      <webElementGuid>308e43ae-0083-4041-9e50-aa62ca1f18e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='수정'])[3]/following::button[1]</value>
      <webElementGuid>403249c4-048b-4bba-9271-b4a3f1711908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='키워드 삭제'])[6]/following::button[2]</value>
      <webElementGuid>590cbfc5-d34a-44ec-903f-fe75e40c3f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='우편번호 검색 : WAP-CORP-0025'])[1]/preceding::button[1]</value>
      <webElementGuid>69cca25d-df27-4bd6-897e-30f6fa812aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='입력 삭제'])[7]/preceding::button[1]</value>
      <webElementGuid>856b77c5-e766-417c-a4cd-285b5cc83c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/section/button</value>
      <webElementGuid>fa40f0d6-2c3e-4ef4-9549-a7bbd32fef7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '닫기' or . = '닫기')]</value>
      <webElementGuid>2dc24a6b-3983-482b-bb65-085d8b70dcfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
