<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>4c96f72f-bb4b-4bd5-934c-bf05dc420977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='ORPA002_validation()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.popup__container.popup__size-l.isShow > div.popup__btn-wrap > button.base-btn.type1__size-m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;수정&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a98ec29-b510-4daf-b1d1-3690cc687692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type1__size-m</value>
      <webElementGuid>d6aa3de2-bca5-4990-815f-d16ab7236e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ORPA002_validation()</value>
      <webElementGuid>af5c10ad-b10d-4f18-88d3-8b1b0883c356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>수정</value>
      <webElementGuid>54583f5e-6e22-4688-9162-243f9b0a587c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;isLayerShow&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;layer-popup type-modal isShow&quot;]/section[@class=&quot;popup__container popup__size-l isShow&quot;]/div[@class=&quot;popup__btn-wrap&quot;]/button[@class=&quot;base-btn type1__size-m&quot;]</value>
      <webElementGuid>5e0361f7-a981-4a7e-ae01-ee77049590e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='ORPA002_validation()']</value>
      <webElementGuid>0450df1b-db8b-41af-b807-c81253474a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='키워드 삭제'])[6]/following::button[1]</value>
      <webElementGuid>7d57d2a7-b83a-4752-ae39-c0bd1cf6b986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업 홈페이지'])[2]/following::button[2]</value>
      <webElementGuid>a4cb3dce-3739-47cb-8d08-91be9ada9e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='닫기'])[2]/preceding::button[1]</value>
      <webElementGuid>64ab3593-a113-47fe-ae5a-8769b9805dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='우편번호 검색 : WAP-CORP-0025'])[1]/preceding::button[2]</value>
      <webElementGuid>fb468e05-3fb6-44e5-b966-df8ef8e38c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/section/div[3]/button</value>
      <webElementGuid>67400700-1a11-4d4b-9187-651f8ee5f246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '수정' or . = '수정')]</value>
      <webElementGuid>18b69c7d-afbd-4a2d-8baa-abfd99a4d9b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
