<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__companyNm</name>
   <tag></tag>
   <elementGuidId>3b51b47a-2d95-4479-9ed0-ae5ed6b42594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyNm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-box > #companyNm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;기업명을 입력해주세요&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6410b510-8529-47a9-97be-81e803d85b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6717d3e-b9f9-40a9-8645-b81a198c926c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyNm</value>
      <webElementGuid>9ab6b2e8-dd87-4411-952a-7a691119545f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyNm</value>
      <webElementGuid>74a38cb9-098e-4c37-95ba-21236e85ffb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt</value>
      <webElementGuid>5af8a228-2fba-4c9f-aa9e-e4ac97aafea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>기업명을 입력해주세요</value>
      <webElementGuid>fd484115-1e81-4cb8-8970-48f9174d593a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>inputValueChk()</value>
      <webElementGuid>45de591b-5a87-4ca3-b228-de90db4232be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formInsert&quot;)/div[@class=&quot;box-flex type-gap2&quot;]/div[@class=&quot;box-flex__cell&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-inner&quot;]/div[@class=&quot;input-box&quot;]/input[@id=&quot;companyNm&quot;]</value>
      <webElementGuid>3f79c463-bd2d-4fdf-a2f4-984f5f1f9b10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyNm']</value>
      <webElementGuid>98a29028-cb3b-4246-bcf4-aac8ec50a721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formInsert']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>0cfa22ba-25b0-4fa5-858f-0010ee903d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>6da374cd-cc27-440d-9175-8c783dccde83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'companyNm' and @name = 'companyNm' and @placeholder = '기업명을 입력해주세요']</value>
      <webElementGuid>fdebb361-7d85-4132-8228-88d0f82d14b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
