<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__2기업정보화면-기업명</name>
   <tag></tag>
   <elementGuidId>f771ac84-e2bc-4c4f-a3c8-da5fad4d101e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='companyNm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#companyNm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[@class=&quot;wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;contents&quot;]/div[@class=&quot;box-type1 relative-box&quot;]/div[@class=&quot;box-flex type-gap3&quot;]/div[@class=&quot;dashboard__corp-info3&quot;]/p[@class=&quot;info-item&quot;]/span[@id=&quot;companyNm&quot;][count(. | //span[@id = 'companyNm' and @class = 'val' and (text() = '아던트_계열사2' or . = '아던트_계열사2')]) = count(//span[@id = 'companyNm' and @class = 'val' and (text() = '아던트_계열사2' or . = '아던트_계열사2')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;아던트_계열사2&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5be4b073-9db1-413e-8a53-71446a28f359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyNm</value>
      <webElementGuid>fc85892a-edd5-4a35-bff2-f8c64bdb348a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>val</value>
      <webElementGuid>3d663404-42c6-4623-a803-0b890433fa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>아던트_계열사2</value>
      <webElementGuid>cca6128e-510d-4945-8287-64eeaac82d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;contents&quot;]/div[@class=&quot;box-type1 relative-box&quot;]/div[@class=&quot;box-flex type-gap3&quot;]/div[@class=&quot;dashboard__corp-info3&quot;]/p[@class=&quot;info-item&quot;]/span[@id=&quot;companyNm&quot;]</value>
      <webElementGuid>53b5a3ef-589d-491c-8373-ffeb41cd00f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='companyNm']</value>
      <webElementGuid>d7251341-b795-4ee6-aae3-6f9f78f6d19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업명'])[1]/following::span[1]</value>
      <webElementGuid>e5996353-b7ef-46e9-b1de-b54feeafd313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업정보'])[3]/following::span[2]</value>
      <webElementGuid>6a6f1bfe-16ba-4875-b57c-7e3cb86ee14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사업자 등록번호'])[1]/preceding::span[1]</value>
      <webElementGuid>6e10f3cf-8bce-420a-b60f-0f7f6d8d99d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='주소'])[1]/preceding::span[3]</value>
      <webElementGuid>0cce1e68-72aa-4a35-a114-b0e7dedf396a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='아던트_계열사2']/parent::*</value>
      <webElementGuid>827d0bc0-bf4f-47ed-803e-881246ac47a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span[2]</value>
      <webElementGuid>659205e9-8d17-43f9-aef1-19f20b2e0155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'companyNm' and (text() = '아던트_계열사2' or . = '아던트_계열사2')]</value>
      <webElementGuid>cc3e2bf6-4c18-41c5-a804-c71446760415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
