<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>36d048ee-0edc-48fc-9f90-848b58b9f3a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0010-ClauseRow12-OpenPopup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='WAP-EMPL-0010-ClauseRow12-OpenPopup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#WAP-EMPL-0010-ClauseRow12-OpenPopup</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51a56d14-8079-4675-ad15-e31438051986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type3</value>
      <webElementGuid>c5890165-d556-44c9-8107-0af2b091cc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0010-ClauseRow12-OpenPopup</value>
      <webElementGuid>6c638e57-6e25-42b2-8c7d-0cc572462667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>WAP_EMPL_0013_OpenPopup(1125,12)</value>
      <webElementGuid>5b6f07e8-acef-4e4c-a6d6-2388ae1c0a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>설정</value>
      <webElementGuid>c094f666-caa0-41dc-a5d0-0d2756185359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0010-ClauseRow12-OpenPopup&quot;)</value>
      <webElementGuid>f152027d-490f-43d5-a834-334659b573a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='WAP-EMPL-0010-ClauseRow12-OpenPopup']</value>
      <webElementGuid>59729213-82bb-4754-89d0-e0798ec8f3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clauseRow_12']/div[2]/div/button</value>
      <webElementGuid>82cac823-614b-4887-8399-0fa0e37389af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='모두 사용'])[3]/following::button[1]</value>
      <webElementGuid>1cf49886-ffcb-4aa7-925b-254ab6cc8d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='약관수정테스트_기업관리자33'])[1]/following::button[1]</value>
      <webElementGuid>24f0adbf-2f62-41e1-9648-cef78efb5a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='버튼'])[5]/preceding::button[1]</value>
      <webElementGuid>59ae16c8-4d95-4b59-8d3c-d30a0d14e666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='일반직'])[4]/preceding::button[1]</value>
      <webElementGuid>cbc673a7-22b4-4a51-9fc9-9b8d8991edfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='설정']/parent::*</value>
      <webElementGuid>095d2885-f64e-4002-8fc8-71cd9670c911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div[2]/div/div[2]/div/button</value>
      <webElementGuid>bf68d6c9-52d9-4f3d-a2f0-981807b75b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'WAP-EMPL-0010-ClauseRow12-OpenPopup' and (text() = '설정' or . = '설정')]</value>
      <webElementGuid>7892de79-a00b-4e79-9522-8199435d7335</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
