<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>3fa6c3b9-faf0-46e1-81b3-23dfb2583251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0010-ClauseRow0-OpenPopup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='WAP-EMPL-0010-ClauseRow0-OpenPopup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#WAP-EMPL-0010-ClauseRow0-OpenPopup</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1bfd037-de5b-47af-b646-7878560de1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type3</value>
      <webElementGuid>030c2faf-a201-43fc-8bfd-b1508c4000a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0010-ClauseRow0-OpenPopup</value>
      <webElementGuid>0c2867a9-ae52-4d06-ae21-a1d722cbbf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>WAP_EMPL_0013_OpenPopup(1125,0)</value>
      <webElementGuid>82b53a2a-f58e-4801-918c-40503fda733f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>설정</value>
      <webElementGuid>0d22b73e-253d-40c0-b4ab-9bb379c06da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0010-ClauseRow0-OpenPopup&quot;)</value>
      <webElementGuid>82d99256-1ff9-417b-be5c-e16d3a1ca917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='WAP-EMPL-0010-ClauseRow0-OpenPopup']</value>
      <webElementGuid>44bfca86-585f-4a37-bd23-264999218990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clauseRow_0']/div[2]/div/button</value>
      <webElementGuid>24e45b0c-ea16-43f2-ab62-353cea7842fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='모두 사용'])[6]/following::button[1]</value>
      <webElementGuid>92f1fa7f-1930-48a7-b53e-cd01db2224c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='버튼'])[11]/preceding::button[1]</value>
      <webElementGuid>913ba6de-fe47-4bdd-bed7-cf6979f7b403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사무직'])[7]/preceding::button[1]</value>
      <webElementGuid>ebc0ab86-e987-4db5-bbfa-c194d9325373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/button</value>
      <webElementGuid>3affac97-ff4a-465f-ac35-21c7c3e2f2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'WAP-EMPL-0010-ClauseRow0-OpenPopup' and (text() = '설정' or . = '설정')]</value>
      <webElementGuid>57060d92-553b-4451-853f-f6e2ade9b8db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
