<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3</name>
   <tag></tag>
   <elementGuidId>f3a9737b-cd95-4fda-8c0a-eab4dc30a6aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0013-Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='WAP-EMPL-0013-Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#WAP-EMPL-0013-Save</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d42988a-837f-427b-aa75-79b5261b6552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-btn type2__size-m</value>
      <webElementGuid>b871cfc7-f260-45c4-8a94-0e75e8d120d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0013-Save</value>
      <webElementGuid>2969dfbf-e44f-4ac2-b5b4-d05e889cdbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>WAP_EMPL_0013_FnSave(1125,0)</value>
      <webElementGuid>6ca5f42f-5d81-448d-b66a-98d7e659cfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>저장</value>
      <webElementGuid>4584de6a-782f-4433-a000-dbaf5758737b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0013-Save&quot;)</value>
      <webElementGuid>5fe677f8-edff-4e06-93ca-b9221e211c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='WAP-EMPL-0013-Save']</value>
      <webElementGuid>51d0f73b-b1db-4553-99e5-154e10998287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전체삭제'])[1]/following::button[1]</value>
      <webElementGuid>ee43c443-d0ec-461c-9026-1a222eec5008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='닫기'])[4]/preceding::button[1]</value>
      <webElementGuid>145ae2a1-01a8-4b1b-9df3-d3afb13a2b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer 영역입니다.'])[1]/preceding::button[2]</value>
      <webElementGuid>e5536694-ff7d-48de-b007-acb59be331f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/section/div[3]/button</value>
      <webElementGuid>361dd6cd-9226-4623-bf4d-7575410e7b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'WAP-EMPL-0013-Save' and (text() = '저장' or . = '저장')]</value>
      <webElementGuid>2ec10bd3-cb52-428f-aca4-dba97d346445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
