<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__calendar1_2</name>
   <tag></tag>
   <elementGuidId>a0987dda-f46b-4c8c-96e8-531c2d19035f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendar1_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calendar1_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#calendar1_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3820378-db1d-4a6b-ac95-80fed0a660ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8def9bd0-d166-4f4a-86f2-e1fcca1e021f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt datepicker-input</value>
      <webElementGuid>991a04c0-2fe9-45f0-9f1b-87d380a4707b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar1_2</value>
      <webElementGuid>5531fef4-34d1-4f0d-ac76-5e2c1b99bb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>일자 선택</value>
      <webElementGuid>3426afa2-7b67-4819-b5f8-eaa0129902f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9828a482-d3c6-4ef1-b4df-2cd756f18e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar1_2&quot;)</value>
      <webElementGuid>771e63c1-d226-4f09-9b2b-0786efb14a3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calendar1_2']</value>
      <webElementGuid>7195fe12-75a3-4957-97c5-856b7914e02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8785866c-da05-4c99-a4c8-6b3a4eca9190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'calendar1_2' and @placeholder = '일자 선택']</value>
      <webElementGuid>1240d8b8-cb49-421c-a6ef-7a543d3dcd8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
