<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__calendar1_1</name>
   <tag></tag>
   <elementGuidId>9e709ca2-1e4d-4676-bf2a-7bc388c3f588</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendar1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calendar1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#calendar1_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6d1a1dd-cb0c-4f20-8fab-f5659163fe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef497e48-4119-4968-9646-e5ec27cefbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt datepicker-input</value>
      <webElementGuid>ff8ee97c-2188-4aad-9e0c-7c3430f2bafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar1_1</value>
      <webElementGuid>2585310f-ce27-4792-9938-5e4269eb78e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>일자 선택</value>
      <webElementGuid>5537c5aa-d85b-4be1-b6a0-77b579a8ad66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0cdca5d-c684-4f4e-a33e-19e16f1eb15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar1_1&quot;)</value>
      <webElementGuid>15a169a0-295e-49d4-8af7-9af064d00ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calendar1_1']</value>
      <webElementGuid>6f1790a3-d5d7-4dc2-943a-1aaea966919b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>bf797490-82e3-49f2-853b-b0e904033c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'calendar1_1' and @placeholder = '일자 선택']</value>
      <webElementGuid>3341d99a-df77-48ac-b0d4-02787ea03ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
