<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__WAP-EMPL-0010-RecruitNoticNm</name>
   <tag></tag>
   <elementGuidId>cadb655e-f218-4a2b-8308-8bb992ba4726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0010-RecruitNoticNm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WAP-EMPL-0010-RecruitNoticNm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;채용명을 입력해주세요.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b6e8ce7-53a2-40dc-a938-8bc2f544c730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d527e9ca-0086-42b6-830d-96546c8b3d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt</value>
      <webElementGuid>03ce1fc8-ce79-4011-b706-bc497763cb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0010-RecruitNoticNm</value>
      <webElementGuid>5396c608-5b93-4faa-9449-6afc26cad00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>inputValueChk()</value>
      <webElementGuid>68ba9a29-1aa7-4569-bed6-ac5d39278597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>채용명을 입력해주세요.</value>
      <webElementGuid>0aea87ab-aab9-4c3f-a2a9-18722fc7cb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0010-RecruitNoticNm&quot;)</value>
      <webElementGuid>59339099-be8f-4028-812a-b4ec77a4a209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WAP-EMPL-0010-RecruitNoticNm']</value>
      <webElementGuid>9173e5b3-798c-4ba9-8575-6f31c9f33309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>19409df3-cab1-4bcb-a8ed-20ca1e876fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'WAP-EMPL-0010-RecruitNoticNm' and @placeholder = '채용명을 입력해주세요.']</value>
      <webElementGuid>39b3d04e-c89d-4663-b329-830f51b4dfc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
