<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__departmentName</name>
   <tag></tag>
   <elementGuidId>17e91c20-3ea9-4213-9417-6c3502f1402d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#departmentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='departmentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;채용분야 검색&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f55b75b-5930-406a-8a0f-5d58e87bcd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff0d8e66-b583-48dc-9c83-6f65458b3dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt</value>
      <webElementGuid>219111c8-2602-4792-8d1f-ec72fd28218a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>departmentName</value>
      <webElementGuid>857b028d-a4fc-4a3d-9db2-ad6ddb00544a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>inputValueChk()</value>
      <webElementGuid>9e2b9803-98e7-4dd7-beb4-59553718df70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>채용분야 검색</value>
      <webElementGuid>53d38b57-b6e9-4db3-99b1-c18c98d95d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:if(event.keyCode==13) { addField() }</value>
      <webElementGuid>9aa42c08-25bb-4699-9f92-e4a47edd2474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departmentName&quot;)</value>
      <webElementGuid>c9b55ad9-37cc-416e-8f22-eb32e4126959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='departmentName']</value>
      <webElementGuid>7bb8b506-ea3f-499b-a94b-2e3c8869780a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>4b79970a-dd17-43e4-b496-8ea810a9e028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'departmentName' and @placeholder = '채용분야 검색']</value>
      <webElementGuid>fbda3ae3-1ef7-473c-8859-d6573d3d0e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
