<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__WAP-EMPL-0010-RecruitNoticNm</name>
   <tag></tag>
   <elementGuidId>bfc9254d-8fd9-4288-9210-9c0fce38b734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0010-RecruitNoticNm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WAP-EMPL-0010-RecruitNoticNm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;채용명을 입력해주세요.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d37b14f-1190-49f8-8b1b-ff5d0b8992f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>224aa473-a375-46ac-80b4-42d9bdc0b21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-txt</value>
      <webElementGuid>cb3e012b-55a0-44db-a42a-fddd52d8c008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0010-RecruitNoticNm</value>
      <webElementGuid>84480836-ec03-4cfa-a179-ab89d453e520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>inputValueChk()</value>
      <webElementGuid>7250a3bc-cc1b-4c01-b542-43bc09b4ffcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>채용명을 입력해주세요.</value>
      <webElementGuid>221c2049-240a-4286-ba74-bdd71c823de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0010-RecruitNoticNm&quot;)</value>
      <webElementGuid>4999a8d8-9b01-4b7e-9b26-d3a47bede819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WAP-EMPL-0010-RecruitNoticNm']</value>
      <webElementGuid>92db6cc9-da70-42d2-bb36-5b5146abe0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>64455cd2-b303-480e-b268-9cad24f95e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'WAP-EMPL-0010-RecruitNoticNm' and @placeholder = '채용명을 입력해주세요.']</value>
      <webElementGuid>110aa9a7-3552-49e7-95e9-5df844945cd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
