<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2</name>
   <tag></tag>
   <elementGuidId>1556e7a2-1f7b-41b4-bfd8-856e4615de9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#label_field_document1_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='label_field_document1_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#label_field_document1_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2d944e3c-542b-4abf-88d9-57ffd874e2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>53b08e1b-fa47-4c2f-a1e6-a452d64ebbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label_field_document1_2</value>
      <webElementGuid>4ce18b49-df7e-4846-8545-324ad95d37b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>분야 명 2</value>
      <webElementGuid>5e98b594-038d-4eb7-82b5-3c95f71fbce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label_field_document1_2&quot;)</value>
      <webElementGuid>dd9153ec-3048-4ef5-896f-6ddd2da7518f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='label_field_document1_2']</value>
      <webElementGuid>128d4e7c-7403-4994-b72d-3fd3a7b6a3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='p_field_document1_2']/span</value>
      <webElementGuid>85e22f6c-31d8-4c41-8da4-a8fa55d9136e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='버튼'])[1]/following::span[1]</value>
      <webElementGuid>03a102da-901d-41a0-a5f5-1cda4bd7d654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='분야 명 1'])[2]/following::span[2]</value>
      <webElementGuid>61bcd4cc-4f62-47aa-91e4-07228a0a90d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='버튼'])[2]/preceding::span[1]</value>
      <webElementGuid>6f50b28c-d453-45f6-88f9-6577fcc881fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='분야 명 3'])[2]/preceding::span[2]</value>
      <webElementGuid>7183c4ab-82b2-45ae-bafd-c5b8a6b2de27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/span</value>
      <webElementGuid>2268a80d-2e87-4185-9c9c-c60ca4c42aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'label_field_document1_2' and (text() = '분야 명 2' or . = '분야 명 2')]</value>
      <webElementGuid>6020bf7d-f948-421d-9c25-3f2cedbbf54f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
