<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1_2</name>
   <tag></tag>
   <elementGuidId>1c10c9fe-487f-43ce-a7b2-d53b989f8a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.base-icon.icon-add__color1__size-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='WAP-EMPL-0010-ScrnAddDocument']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;서류전형&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32dada2d-4ffe-4144-b998-0d056a3a6bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-icon icon-add__color1__size-s</value>
      <webElementGuid>f427d29c-a438-416e-a763-11fc2d23516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>서류전형</value>
      <webElementGuid>fce090cc-b66f-4705-9f36-efa04271aefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0010-ScrnAddDocument&quot;)/span[@class=&quot;base-icon icon-add__color1__size-s&quot;]</value>
      <webElementGuid>d4afd459-8dc9-4e3d-bfae-a16f047d00cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='WAP-EMPL-0010-ScrnAddDocument']/span</value>
      <webElementGuid>e59fb074-451f-4f5c-bc31-41eef9b176a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전형 추가'])[1]/following::span[1]</value>
      <webElementGuid>5b798915-d700-49c5-a8f8-206eb28d07d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전형설계'])[2]/following::span[1]</value>
      <webElementGuid>9877f7db-970c-4bde-9d9b-bed7eee6b45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='필기전형'])[1]/preceding::span[1]</value>
      <webElementGuid>bfad9b24-2bac-40ad-bc0d-69123a8182c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='면접전형'])[1]/preceding::span[2]</value>
      <webElementGuid>e525aa63-ef90-457a-96f5-6c989b957a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='서류전형']/parent::*</value>
      <webElementGuid>87b5e97e-67d4-4143-9596-a5207de421ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>30dff39c-06b9-4e72-97bb-71f62c454b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '서류전형' or . = '서류전형')]</value>
      <webElementGuid>578aac99-86b2-4054-9336-9726fe27580a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
