<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_</name>
   <tag></tag>
   <elementGuidId>fc3e7449-a7ae-4ee0-a437-742dc7f42efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='WAP-EMPL-0011-Table']/tbody/tr[3]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;선택 724 [test] 채용공고등록테스트240305-1 2024.02.26~2024.03.04 3개 분야&quot;i] >> internal:role=cell >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>25fedf44-3b3f-42b6-aa6b-083471a515e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  dt-head-center</value>
      <webElementGuid>5c4ed47c-1cca-464e-9597-0228a480403a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  선택 </value>
      <webElementGuid>50c0eaac-6f08-41be-9534-b132efe49693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0011-Table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-head-center&quot;]</value>
      <webElementGuid>8b752058-e3e4-4c66-bf3d-3a5e19ff3592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='WAP-EMPL-0011-Table']/tbody/tr[3]/td</value>
      <webElementGuid>2bbdba62-4b05-4084-80b2-86cd2b6f8b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='면접전형테스트용'])[1]/following::td[3]</value>
      <webElementGuid>585b2d49-ea1b-4119-946a-e5c3035218fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='선택'])[3]/following::td[5]</value>
      <webElementGuid>1654af8a-cc51-4eb1-8dd7-b61094d6f347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[test] 채용공고등록테스트240305-1'])[1]/preceding::td[2]</value>
      <webElementGuid>5881b579-6b38-4323-ad2f-57701795ebcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>58d4b108-266f-4b70-b36d-b7744b6e9066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '  선택 ' or . = '  선택 ')]</value>
      <webElementGuid>54ea3526-6479-4887-8379-d9637d6f4b2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
