<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1</name>
   <tag></tag>
   <elementGuidId>ce47ed50-85fb-462d-938e-66c35e012736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='WAP-EMPL-0011-Table']/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;[김준영] 정량평가 테스트 공고명&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6840b7ce-2359-48a8-9544-949d0718c59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  dt-head-center</value>
      <webElementGuid>03f1d889-61f8-4e2d-a335-862e3bf282eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[김준영] 정량평가 테스트 공고명</value>
      <webElementGuid>5c7509e8-11c6-47fd-8d50-36668f9f8421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0011-Table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-head-center&quot;]</value>
      <webElementGuid>87730bec-eceb-4ef2-8ad1-ff4f9af21082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='WAP-EMPL-0011-Table']/tbody/tr/td[3]</value>
      <webElementGuid>3d58df81-7d49-4b95-ae7f-0cf8c9624138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='선택'])[2]/following::td[2]</value>
      <webElementGuid>24bd4ee4-c575-41c6-bd0e-8f1aeb8a7d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='채용분야'])[2]/following::td[3]</value>
      <webElementGuid>9ad57eb7-2703-4f9c-9a5b-e5f0ee84eed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='선택'])[3]/preceding::td[3]</value>
      <webElementGuid>62ec94c3-2193-4678-9771-b08193ea3959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='면접전형테스트용'])[1]/preceding::td[5]</value>
      <webElementGuid>54484413-611e-4750-82c3-20d9553016cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[김준영] 정량평가 테스트 공고명']/parent::*</value>
      <webElementGuid>79e5a0b8-fe6f-416d-8d3a-5c91d6be5f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>077846c9-7c10-43ba-ad36-40ab519d9b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '[김준영] 정량평가 테스트 공고명' or . = '[김준영] 정량평가 테스트 공고명')]</value>
      <webElementGuid>13ec98ae-3876-4d22-8611-449b72c5623d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
