<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>전형관리홈_공고명</name>
   <tag></tag>
   <elementGuidId>114ecbb9-bb7c-471a-9b97-44d712f8f121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='WAP-EMPL-0030-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0030-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;[test] 채용공고등록테스트240305&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>381fece1-ce26-44e2-aa64-ad00cc7db38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-title</value>
      <webElementGuid>cef0d829-3fee-4a79-aeab-c4ff9ac12cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0030-Title</value>
      <webElementGuid>dacf2ac8-d975-489c-a42d-56ca4f9f84c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[test] 채용공고등록테스트240305</value>
      <webElementGuid>8641b44c-7ee1-4b3a-bf88-bc8acd24933a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0030-Title&quot;)</value>
      <webElementGuid>124d94f2-8b42-4acb-9001-c94b58f7b599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='WAP-EMPL-0030-Title']</value>
      <webElementGuid>5f472258-69f0-49c1-aa66-0250c85cf4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='홈'])[2]/following::h4[1]</value>
      <webElementGuid>7a048f1e-6baa-429f-826b-0ebb3ffe496c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='통계'])[1]/following::h4[1]</value>
      <webElementGuid>d64ca9a7-cf9c-4435-bf03-80947099f32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='채용정보 수정'])[1]/preceding::h4[1]</value>
      <webElementGuid>bb272bc7-20fd-4108-aac6-47535f0fb51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='알림설정'])[1]/preceding::h4[1]</value>
      <webElementGuid>3571ace6-91e2-4caa-a2b1-48e192fd4708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[test] 채용공고등록테스트240305']/parent::*</value>
      <webElementGuid>22162afe-4a0e-4b9a-a5cd-6077e00b651d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>1c8cc9dd-caa5-49fb-bced-95d1a8d630e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'WAP-EMPL-0030-Title' and (text() = '[test] 채용공고등록테스트240305' or . = '[test] 채용공고등록테스트240305')]</value>
      <webElementGuid>d1f67e16-ca2f-463b-a4c5-05fcf5dc4252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
