<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0</name>
   <tag></tag>
   <elementGuidId>ad2e38da-0cab-419d-873f-2cd1514ebc8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='신규'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;0건&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d6c2307c-5f55-4aa3-a8cd-fd7ebca85a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>val point-color</value>
      <webElementGuid>cf4ca703-b33d-4fff-9eff-b4bcdc625314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0건</value>
      <webElementGuid>423e7667-f219-45d0-bbf2-5b117273618f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;contents&quot;]/div[@class=&quot;box-flex type-gap2&quot;]/div[@class=&quot;box-type1 dashboard__corp-box2&quot;]/div[@class=&quot;dashboard__corp-info2&quot;]/p[@class=&quot;info-item&quot;]/span[@class=&quot;val point-color&quot;]</value>
      <webElementGuid>c69f1327-1489-4be1-83fb-09b3b49594ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='신규'])[1]/following::span[1]</value>
      <webElementGuid>ae297a53-bbf7-4146-9813-ff0ddea4811b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='시스템 공지사항'])[1]/following::span[2]</value>
      <webElementGuid>2c96b027-5d85-447a-a5e3-8e8f9690b799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전체 채용'])[1]/preceding::span[2]</value>
      <webElementGuid>1fae6760-7231-4c56-8d0c-a43b1c9780ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='종료'])[2]/preceding::span[2]</value>
      <webElementGuid>589e13a9-fd5e-47f5-ae41-68ff518f3879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p/span[2]</value>
      <webElementGuid>72058ea9-0ed5-4286-836c-53631b9e68ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0건' or . = '0건')]</value>
      <webElementGuid>1e2915b0-fbe6-4fa4-bee9-01d324613c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
