<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_</name>
   <tag></tag>
   <elementGuidId>510fc9fa-2f60-4386-b53f-341239d6c2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WAP-EMPL-0030-Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='WAP-EMPL-0030-Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;[김준영] 정량평가 테스트 공고명&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>079d2cc3-55eb-4c47-a9ab-75565c9a96eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-title</value>
      <webElementGuid>0d8340de-28ae-4cd0-947a-86e9c3701c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WAP-EMPL-0030-Title</value>
      <webElementGuid>7f3d937f-7932-480d-9ac9-cd872ec4efbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[김준영] 정량평가 테스트 공고명</value>
      <webElementGuid>1c9bf440-9c15-4d20-9895-12dbe11c84f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WAP-EMPL-0030-Title&quot;)</value>
      <webElementGuid>e230ebce-3550-4f1a-add5-6c17c861adfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='WAP-EMPL-0030-Title']</value>
      <webElementGuid>ad0824f9-7315-4929-a464-d34ed6e4aebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='홈'])[2]/following::h4[1]</value>
      <webElementGuid>2e8a1c7b-6ed3-4126-9780-2730311c268a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='통계'])[1]/following::h4[1]</value>
      <webElementGuid>124c32ff-1cc4-44c9-94de-2bc516f94c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='채용정보 수정'])[1]/preceding::h4[1]</value>
      <webElementGuid>5938b3a9-5bb4-4771-a276-ddb06b470502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='알림설정'])[1]/preceding::h4[1]</value>
      <webElementGuid>4780ffde-8ef4-4697-8191-7f04732508ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[김준영] 정량평가 테스트 공고명']/parent::*</value>
      <webElementGuid>feb780f9-9da6-4345-a7d0-ce5c0de340ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>6d3e526c-4b98-40c3-9fd6-b4f8ceec6525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'WAP-EMPL-0030-Title' and (text() = '[김준영] 정량평가 테스트 공고명' or . = '[김준영] 정량평가 테스트 공고명')]</value>
      <webElementGuid>e48d132a-7cbe-4f71-a445-03fae37e4787</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
