<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>21589579-0d61-43c3-be66-9252b5cf2856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snbSubMenu10']/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.isMark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;권한관리&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba4464a2-66c9-4194-8411-31f9364b86b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/orp/management/auth/list.do?menuId=40000400</value>
      <webElementGuid>5791af5c-1f70-49f8-9207-5e0dadee4439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>isMark</value>
      <webElementGuid>f6379850-108d-4a16-b686-a541c157ca9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>권한관리
            </value>
      <webElementGuid>fc90e000-ea4e-4777-9ff3-23666d3546c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snbSubMenu10&quot;)/ul[1]/li[4]/a[@class=&quot;isMark&quot;]</value>
      <webElementGuid>ad0f813a-54b5-43c4-96a2-7a1272ca355c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='snbSubMenu10']/ul/li[4]/a</value>
      <webElementGuid>7c4af8da-ee09-44a8-bd0f-5410897b35c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'권한관리')]</value>
      <webElementGuid>480a59cb-7d81-40c8-b7a8-2f6bd31edddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사용자관리'])[1]/following::a[1]</value>
      <webElementGuid>c5212ee6-5fa0-4b10-a922-4c3425b884a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='팝업관리'])[1]/following::a[2]</value>
      <webElementGuid>ca823575-8316-4214-82b0-c7f7854b318f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말관리'])[1]/preceding::a[1]</value>
      <webElementGuid>a936fad8-29c7-4a73-9876-1e6c9baa3cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='접속기록'])[1]/preceding::a[2]</value>
      <webElementGuid>13779675-f45e-41e7-93fd-78d093b22de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='권한관리']/parent::*</value>
      <webElementGuid>3f0fcc7a-cbbb-49db-bb46-8055213c0460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/orp/management/auth/list.do?menuId=40000400')]</value>
      <webElementGuid>93226d98-a559-4f21-9982-15db2c0d8e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[4]/a</value>
      <webElementGuid>5cb3fa29-4329-4f26-a3f1-1636873ae66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/orp/management/auth/list.do?menuId=40000400' and (text() = '권한관리
            ' or . = '권한관리
            ')]</value>
      <webElementGuid>122d1430-5f99-4035-bad4-28eff6bc1592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
